# Generated by Django 4.2.7 on 2025-12-08 07:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Job title", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier (auto-generated from title if not provided)",
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department name (e.g., Engineering, Marketing)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Job location (e.g., Remote, New York, London)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full-time", "Full Time"),
                            ("part-time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        help_text="Job type",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Job description (HTML content)"),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="Job requirements (HTML content)",
                        null=True,
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True,
                        help_text="Job responsibilities (HTML content)",
                        null=True,
                    ),
                ),
                (
                    "application_email",
                    models.EmailField(
                        help_text="Email address for job applications",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "application_method",
                    models.TextField(
                        blank=True,
                        help_text="Custom application instructions (HTML content)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the job is active/visible"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Whether the job is featured"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, help_text="When the job was posted", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the job expires", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "jobs",
                "ordering": ["-is_featured", "-posted_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="jobs_slug_874285_idx"),
                    models.Index(fields=["is_active"], name="jobs_is_acti_887823_idx"),
                    models.Index(
                        fields=["is_featured"], name="jobs_is_feat_21eb11_idx"
                    ),
                    models.Index(fields=["department"], name="jobs_departm_c1872d_idx"),
                    models.Index(fields=["location"], name="jobs_locatio_8650dd_idx"),
                    models.Index(fields=["type"], name="jobs_type_c0d598_idx"),
                    models.Index(fields=["expires_at"], name="jobs_expires_503a37_idx"),
                ],
            },
        ),
    ]
