# Generated by Django 4.2.7 on 2025-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversationsession_email_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="apply_url",
            field=models.URLField(
                blank=True,
                help_text="Official application page URL",
                max_length=500,
                null=True,
            ),
        ),
    ]
