# Generated by Django 4.2.7 on 2025-11-30 08:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0002_conversationsession_email_response_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CounselorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Senior Education Consultant",
                        max_length=100,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Professional biography and experience"
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of specialization areas, e.g., ['UK Universities', 'STEM Programs']",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="counselors/profiles/"
                    ),
                ),
                (
                    "meeting_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Default session duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Default video meeting link (Zoom, Google Meet, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether counselor is accepting new bookings",
                    ),
                ),
                (
                    "max_daily_sessions",
                    models.PositiveIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Counselor Profile",
                "verbose_name_plural": "Counselor Profiles",
                "db_table": "counselor_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public booking reference ID",
                        unique=True,
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_phone", models.CharField(blank=True, max_length=20)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Consultation"),
                            ("followup", "Follow-up Session"),
                            ("document_review", "Document Review"),
                            ("application_help", "Application Assistance"),
                            ("visa_guidance", "Visa Guidance"),
                            ("general", "General Inquiry"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="Video call link for the session"
                    ),
                ),
                (
                    "meeting_notes",
                    models.TextField(
                        blank=True, help_text="Pre-session notes or agenda from student"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verification_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Token for email verification and booking management",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether student email has been verified",
                    ),
                ),
                (
                    "counselor_notes",
                    models.TextField(
                        blank=True, help_text="Notes from counselor after session"
                    ),
                ),
                ("student_feedback", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student", "Student"),
                            ("counselor", "Counselor"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to chat conversation if booking originated from chat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="chat.conversationsession",
                    ),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="booking.counselorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Session",
                "verbose_name_plural": "Booking Sessions",
                "db_table": "booking_sessions",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="BookingReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Booking Confirmation"),
                            ("reminder_24h", "24 Hour Reminder"),
                            ("reminder_1h", "1 Hour Reminder"),
                            ("followup", "Post-Session Follow-up"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("sent_to", models.EmailField(max_length=254)),
                ("was_successful", models.BooleanField(default=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="booking.bookingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Reminder",
                "verbose_name_plural": "Booking Reminders",
                "db_table": "booking_reminders",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="CounselorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of the week (for recurring availability)",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time of availability window"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="End time of availability window"),
                ),
                (
                    "specific_date",
                    models.DateField(
                        blank=True,
                        help_text="If set, this availability applies only to this specific date",
                        null=True,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="False = blocked/unavailable during this time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="booking.counselorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counselor Availability",
                "verbose_name_plural": "Counselor Availabilities",
                "db_table": "counselor_availabilities",
                "ordering": ["weekday", "start_time"],
                "unique_together": {
                    ("counselor", "weekday", "start_time", "end_time", "specific_date")
                },
            },
        ),
        migrations.AddIndex(
            model_name="bookingsession",
            index=models.Index(
                fields=["booking_id"], name="booking_ses_booking_cb44b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingsession",
            index=models.Index(
                fields=["student_email"], name="booking_ses_student_17e5d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingsession",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="booking_ses_status_9d1f3a_idx",
            ),
        ),
    ]
