# Generated by Django 4.2.7 on 2025-12-20 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the news source (e.g., BBC, CNN)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo of the news source",
                        null=True,
                        upload_to="blog/sources/",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True, help_text="Official website URL of the source"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the news source"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Mark as verified/trusted source"
                    ),
                ),
                (
                    "credibility_score",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Credibility score from 1-10",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News Source",
                "verbose_name_plural": "News Sources",
                "db_table": "blog_news_sources",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="Original article URL from the source"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="News source for authenticity (e.g., BBC, CNN)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.newssource",
            ),
        ),
    ]
