# Generated by Django 4.2.7 on 2025-12-26 10:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_newssource_blogpost_source_url_blogpost_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPostReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or description of the reference source",
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL link to the reference source", max_length=2048
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Author of the referenced content (optional)",
                        max_length=255,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        help_text="Publication date of the reference (optional)",
                        null=True,
                    ),
                ),
                (
                    "accessed_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the reference was accessed (optional)",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description or note about this reference (optional)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of the reference (0-9)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The blog post this reference belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post Reference",
                "verbose_name_plural": "Blog Post References",
                "db_table": "blog_post_references",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "order"], name="blog_post_r_post_id_eeb83c_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="blogpostreference",
            constraint=models.UniqueConstraint(
                fields=("post", "order"), name="unique_reference_order_per_post"
            ),
        ),
    ]
